2021 update 3
whereby/policy pull request #36
Opened 2021-02-17 08:50 UTC by jonaslybechjensen

2021-02-17 13:58 UTC, ingridod commented on privacy-policy.md
>  Gate 1 no. 101, 6700 Måløy, Norway
no. 107

2021-02-17 13:59 UTC, ingridod commented on privacy-policy.md
>  need additional features on top of the FREE version, and does not rely
Free version

2021-02-17 13:59 UTC, ingridod commented on privacy-policy.md
>  Gate 1 no. 101, 6700 Måløy, Norway
no. 107

2021-02-17 14:00 UTC, ingridod commented on privacy-policy.md
>  need additional features on top of the FREE version, and does not rely
Free version

2021-02-17 14:06 UTC, ingridod commented on privacy-policy.md
> +  information about you if you have a linkedIn profile. We use this
LinkedIn

2021-02-17 14:07 UTC, ingridod commented on privacy-policy.md
> +  your account) as they are necessary information for the Services
Missing a point . at the end?

2021-02-17 14:10 UTC, ingridod commented on privacy-policy.md
> +In the FREE version of the Services, users can use “Small meeting” mode
Free

2021-02-17 14:13 UTC, ingridod commented on privacy-policy.md
> +use of our Embedded product in your own service, contact us. We encourage
Link to https://whereby.com/information/embedded/ on "contact us"?

2021-02-17 14:14 UTC, ingridod requested changes
Some smaller things to be changed before merging

2021-04-16 15:04 UTC, closed without merging

2021-04-16 15:04 UTC, jonaslybechjensen commented
Cancelled